name: npm Package

on:
  workflow_call:
    inputs:
      package:
        description: "Path to the project's package.json that should be version bumped"
        type: string
        required: false
        default: './package.json'

jobs:
  version:
    runs-on: ubuntu-latest
    name: Check Version
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Get branch package.json
        id: get_branch_version
        run: |
          branchJsonShell="$(cat ${{ inputs.package }} | tr -d '\n')"
          echo "branchJson=${branchJsonShell}" >> "$GITHUB_OUTPUT"
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get main package.json
        id: get_main_version
        run: |
          mainJsonShell="$(cat ${{ inputs.package }} | tr -d '\n')"
          echo "mainJson=${mainJsonShell}" >> "$GITHUB_OUTPUT"
      - name: Compare branch and main package versions
        run: |
          branchVersion="${{fromJson(steps.get_branch_version.outputs.branchJson).version}}"
          branchMajor="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f1)"
          branchMinor="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f2)"
          branchPatch="$(echo "$branchVersion" | cut -d '-' -f1 | cut -d '.' -f3)"

          mainVersion="${{fromJson(steps.get_main_version.outputs.mainJson).version}}"
          mainMajor="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f1)"
          mainMinor="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f2)"
          mainPatch="$(echo "$mainVersion" | cut -d '-' -f1 | cut -d '.' -f3)"

          echo "Comparing branch version ($branchVersion) and main version: ($mainVersion):"

          if [ "$branchMajor" -gt "$mainMajor" ]; then
            echo "OK"
            exit 0
          elif [ "$branchMajor" -lt "$mainMajor" ]; then
            echo "--> Branch's package major version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          if [ "$branchMinor" -gt "$mainMinor" ]; then
            echo "OK"
            exit 0
          elif [ "$branchMinor" -lt "$mainMinor" ]; then
            echo "--> Branch's package minor version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          if [ "$branchPatch" -gt "$mainPatch" ]; then
            echo "OK"
            exit 0
          elif [ "$branchPatch" -lt "$mainPatch" ]; then
            echo "--> Branch's package patch version ($branchVersion) is out of date with main ($mainVersion) and needs to be updated."
            exit 1
          fi

          echo "--> Branch's package version ($branchVersion) needs to be bumped."
          exit 1
